### ISSUE TITLE
Replace-Objects.jsx

### ISSUE THREAD

**Issue by jxyun99** [daani-rika/Illustrator-scripts#1]
Can you add a feature to let Replace-Objects.jsx support use top-level object replacement?
Thank you！
From Google Translate

**Comment by daani-rika** [comment]
Can you tell me in detail what script should do? Do you mean top object in group or in the layers or something else?

**Comment by jxyun99** [comment]
Now the script uses ClipBoard to replace the object, I want to replace it with the top element in the document

**Comment by jxyun99** [comment]
alexander-ladygin’s script can do this, but his script If the replaced element contains a stroke, the replacement will cause it to be out of center
<img src="https://b1.sbimg.org/file/chevereto-jia/2020/11/27/QDhjG.png" alt="QDhjG.png" border="0" />
<img src="https://b1.sbimg.org/file/chevereto-jia/2020/11/13/GTfUU.jpg" alt="GTfUU.jpg" border="0" />

**Comment by daani-rika** [comment]
[I made a version of the script that works with the top object](https://raw.githubusercontent.com/daani-rika/Illustrator-scripts/master/Replace-Objects-Top-object.jsx). It seems to work correctly with objects with a stroke. 
 
Do you want me to add a checkbox to select the original object or does a separate script fit you?

**Comment by jxyun99** [comment]
use Top-object Replace can work, but even if ignore stroke is selected, the object is still not centered after replacement
<img src="https://b1.sbimg.org/file/chevereto-jia/2020/12/02/Q6kaj.png" alt="Q6kaj.png" border="0" />

**Comment by daani-rika** [comment]
OK, I figured it out — it happens when your target object is a group. If you ungroup it, everything should work all right.

When you group an object, the script cannot detect the stroke and ignores it when calculating a new position. [ It is possible to make a workaround,](https://raw.githubusercontent.com/daani-rika/Illustrator-scripts/master/Replace-Objects-Top-object.jsx) but there may be side effects.

**Comment by jxyun99** [comment]
no， i don't group it
<img src='https://i.postimg.cc/pXbw625k/Replace.gif' border='0' alt='Replace'/>

**Comment by jxyun99** [comment]
[![Replace.gif](https://i.postimg.cc/pXbw625k/Replace.gif)](https://postimg.cc/K4fpKhNg)

**Comment by daani-rika** [comment]
No, I mean one object is group itself. Like this:
![20-12-03_11-23](https://user-images.githubusercontent.com/54983993/100990217-51c31400-355a-11eb-8edc-dafc04e7474d.gif)

**Comment by jxyun99** [comment]
It’s very strange, my rectangle is just a stroke, it is no group itself

**Comment by daani-rika** [comment]
Can you send me your illustrator file? I'll try to find out why the script doesn't work properly.

**Comment by jxyun99** [comment]
I have put the file at https://github.com/jxyun99/test ，I don’t see anything special, it’s just that my AI version is Chinese

**Comment by daani-rika** [comment]
I think, this is a rounding error.[ Please try this version](https://github.com/daani-rika/Illustrator-scripts/blob/master/Replace-Objects-Top-object.jsx) and tell me if it works.

**Comment by jxyun99** [comment]
Now, even if the element is stroke, it can work, but I found other bugs. If the Replacement object is a compound path, it doesn’t work, and if the Replacement object is a group, it doesn’t work。

**Comment by jxyun99** [comment]
<img src="https://github.com/jxyun99/test/blob/main/20201205.gif" alt="20201205.gif">

**Comment by daani-rika** [comment]
As always, I fixed something and broke something :)
[I rewrote half of the script, now it must work with most types of objects.](https://raw.githubusercontent.com/daani-rika/Illustrator-scripts/master/Replace-Objects-1a.jsx)

**Comment by jxyun99** [comment]
Thank you. It can work now!

**Comment by jxyun99** [comment]
Thank！ Is there any way to use this script to replace the object by the name of the linked image?
For example, I want use the selected objects to replace the linked images of selected，the the linked images named is “dog.jpg ”

**Comment by daani-rika** [comment]
I don't quite understand what you want to do, but you need a separate script to replace linked objects. [You can try this script, it replaces all selected linked files with a new one.](https://github.com/dumbm1/ai_scripts/blob/master/jsx/fast_relink.jsx)

**Comment by jxyun99** [comment]
Today, when I tried to replace it with a mask object，I found If the object is a group and contains a mask, it will not work properly（Position error），I tried to modify it myself, but it didn't work。
I collected a function to get the size of the mask object. I wonder if you can try to fix it,thank you!
I have put the file at https://github.com/jxyun99/test
Including test files and GIF demo

**Comment by daani-rika** [comment]
Sorry for delay! 
I fixed this issue and added the option to scale strokes.
I used your function to get the size of the mask. It was very helpful, thank you!
[New version of script is here](https://github.com/daani-rika/Illustrator-scripts/blob/master/Replace-Objects-1a.jsx)
